[package]
name = "inventory"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8", features = ["multipart"] }
tokio = { version = "1", features = ["full"] }
rust_decimal = { version = "1", features = ["db-postgres", "serde"] }
sqlx = { version = "0.9", features = [
    "runtime-tokio",
    "postgres",
    "macros",
    "chrono",
    "uuid",
    "rust_decimal",
] }
tower-http = { version = "0.7.0", features = ["fs"] }
dotenvy = "0.15"
uuid = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
argon2 = "0.5"
jsonwebtoken = { version = "11", default-features = false, features = [
    "rust_crypto",
] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
rand_core = { version = "0.6", features = ["getrandom"] }
rand = "0.10.2"

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"
